### ISSUE TITLE
Unnecessary list of permissions 

### ISSUE THREAD

**Issue by ibrahimAlii** [adbutler/adbutler-android-mraid-sdk#10]
I can see there is a list of permissions, which is shown in google-play..

I'm not sure if there is a real usage for these permissions i.e : location, write/read data etc..

    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />
    <uses-permission android:name="android.permission.SEND_SMS" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by wprevett** [comment]
Hi Ibrahim,

Some of those permissions looks like they were holdovers from our old SDK, I've removed those.  (Network state, Location, Fine Location and External Storage)

The rest are for MRAID support.

Thanks!
