### ISSUE TITLE
VAST Tag XML Structure and Different adTagUrl/apiHostnames

### ISSUE THREAD

**Issue by brandonsabio** [adbutler/adbutler-android-mraid-sdk#16]
Hi, I've been trying to test the VAST video feature with different apiHostnames other than "servedbyadbutler.com" and have adjusted the adTagURL and other sources within the getVideoJSMarkup() function accordingly. When requesting these VAST tags, I keep running into this error:

**I/chromium: [INFO:CONSOLE(0)]** "Uncaught (in promise) AbortError: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22", source: https://examplehostname/ (0)
**I/System.out:** vast://vastresponse?xml=<?xml version="1.0"?><VAST version="2.0"><Ad id="574_1178"><Wrapper><AdSystem version="1.0">Name</AdSystem><VASTAdTagURI>...</VAST>
**I/System.out:** vast://vastresponse?xml=<VAST version="2.0"><Ad id="1234"><InLine><AdSystem>adtags</AdSystem>...</VAST>
**I/libOpenSLES:** Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
**I/cr_MediaCodecBridge:** create MediaCodec video decoder, mime video/avc
**I/OMXClient:** IOmx service obtained
**I/MediaCodec:** MediaCodec will operate in async mode
...
**I/System.out:** error

I was wondering if the cause of this could be that the Vast tag XML structure of the tag is different than that of this servedbyadbutler example tag here: https://servedbyadbutler.com/vast.spark?setID=12394&ID=181442&pid=98086. Could it be a possible error when parsing the XML?

Any help/insight would be much appreciated, thank you!

**Comment by brandonsabio** [comment]
Hi! I just wanted to follow up on this issue and say that I still haven't been able to resolve it.

Again, any help/insight would be much appreciated, thanks!

**Comment by wprevett** [comment]
Hi Brandon.

When you see this error, does it stop the video from playing?

Can you show me the code you have edited?  You can send it to will@adbutler.com if you like.

Thanks
